### ISSUE TITLE
There's no such set as Elves vs. Dragons.

### ISSUE THREAD

**Issue by Psithief** [Sembiance/mtgjson#31]
As possibly the biggest fail of all time — `Duel Decks Anthology: Elves vs. Goblins` is currently in gatherer as `Duel Decks Anthology: Elves vs. Dragons`.

**Comment by Psithief** [comment]
Art for Tranquil Thicket and Wirewood Lodge are switched, though that is more of a mtgimage.com problem.

**Comment by Sembiance** [comment]
Thanks for the heads up. It's fixed. Took care of the image thing over on mtgimage as well. Gatherer for the win!

**Comment by Psithief** [comment]
Thanks!
