### ISSUE TITLE
Duel Decks: Elspeth vs. Kiora is currently on gatherer…

### ISSUE THREAD

**Issue by Psithief** [Sembiance/mtgjson#32]
but it's under the name [`Duel Decks: Kiora vs. Elspeth`](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&set=[%22Duel%20Decks:%20Kiora%20vs.%20Elspeth%22]).

**Comment by Sembiance** [comment]
Added it to MTGJSON. I added it under the correct name. Gatherer is really slipping lately.

**Comment by Sembiance** [comment]
By the way, thanks for the heads up about how the name is wrong :)

**Comment by Psithief** [comment]
> Gatherer is really slipping lately.

Perhaps some lowly data-entry peon at Wizards is very unhappy with his/her job. :)
