### ISSUE TITLE
Gatherer Updated with MM2

### ISSUE THREAD

**Issue by ZeldaZach** [Sembiance/mtgjson#33]
Just thought I'd leave you a note :)

**Comment by Sembiance** [comment]
This update may need to wait a few days. I am currently moving to a new state, over 1,000 miles away and my computer systems are in various boxes and trucks/cars. I'll make this a priority once I get the computer unpacked and set back up.

**Comment by ZeldaZach** [comment]
Gotcha. Thanks for the update!

**Comment by Sembiance** [comment]
Deployed MM2 to MTGJSON :)

**Comment by ZeldaZach** [comment]
Awesome! Thanks for your help @Sembiance :)
