### ISSUE TITLE
Some language's name are not included in AllCards

### ISSUE THREAD

**Issue by hfingler** [Sembiance/mtgjson#34]
Is this a Gatherer or script problem?

 For example, Mana Crypt has no 'foreignLanguages' array even thought there is a pt-BR version of it and Scavenging Ooze has the pt-BR name in the 'portuguese' index, though there is no 'portuguese (Brazil)' index.

 Thanks for the awesome work.

**Comment by Sembiance** [comment]
On gatherer, they don't have any foreign language names for any of the Mana Crypt printings. So it's a Gatherer issue.

In fact, I believe there are a large number of sets and cards that are missing foreign language data on gatherer, even though they were indeed printed in another language.

Does this make sense?

**Comment by hfingler** [comment]
Yeah it does. I know gatherer has some problems but missing names is pretty ridiculous. Thanks.
