### ISSUE TITLE
Ertai the Corrupted 29292 is a promo card. Change set?

### ISSUE THREAD

**Issue by Psithief** [Sembiance/mtgjson#38]
Would you consider changing the set for [Ertai, the Corrupted](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=29292)? 
This is actually a promo card, and should be in one of the promo sets. 
The actual card from the set is [here](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=25614) with id 25614.

**Comment by Sembiance** [comment]
According to the info I have found (http://www.magiclibrarities.net/497-rarities-planeshift-alternate-art-cards-english-cards-english.html) it looks like it was indeed distributed in Planeshift booster packs.

Do you have any information that shows it wasn't in the booster packs? That it was instead distributed exclusively via another channel?

**Comment by Psithief** [comment]
No, sorry. I was only intending 29292 to be marked as a promo so it wouldn't take precedence over 25614 in naive imports.

I looked at the other properties, but there aren't any that seem to capture the problem that the card is a very rare foil-only version.

**Comment by Sembiance** [comment]
I understand what you are saying, but according to my research, BOTH versions of this card were distributed in the original retail Planeshift boosters. This fact thus makes them both part of the actual set and not part of any 'promo' set, regardless of how rare the foil one may be. Or perhaps my research is incorrect? Was the foil card not distributed in the set boosters?

**Comment by Psithief** [comment]
I'm not claiming that you're incorrect. I am closing this now because your dataset doesn't have a property to contain this information.

**Comment by Sembiance** [comment]
I understand now what you are looking for, a field that marks whether or not a card is foilable, or foilOnly, nonFoil, etc. Sorry about the confusion on my part. I have opened up Issue #39 to address this issue.
