### ISSUE TITLE
WPN and Gateway should be split

### ISSUE THREAD

**Issue by Sembiance** [Sembiance/mtgjson#50]
WPN and Gateway were two separate programs, despite magiccards.info combining them into one.  Yes, WPN replaced Gateway, but they are not the same program and right now as they are combined there is no way to determine which set each card is from as the years overlap.

So I should manually figure out which ones were part of which and separate them into pWPN and pGTW

**Comment by jenjia** [comment]
Since I also use magiccards.info to construct my database of images, therefore they are all with code pWPN. Could you share how did you separate them?

**Comment by Sembiance** [comment]
The cards on magiccards.info are sorted correctly by release date. So cards numbered 20 or less are Gateway and those numbered 21 or higher are from WPN.
