### ISSUE TITLE
Add a block identifier to the set lists

### ISSUE THREAD

**Issue by marcobuschini** [Sembiance/mtgjson#72]
I could not find the information about to which block the sets belong, neither in the set files, nor in the card files (I can help with data entry).

**Comment by Sembiance** [comment]
Sets have a 'block' field that lists the block these sets belong to. It is there in both AllSets and the individual set files.

It's only present for 'expansion' sets that are part of blocks.

If you are not seeing it on a particular file that you feel should have it, let me know what file.

**Comment by marcobuschini** [comment]
What I was seeking for is a block-to-set association field so I can build a
user interface with a list of blocks and relative sets without parsing the
whole AllSets file. That is, I would appreciate a block field in the
SetList.json file.

Il giorno lun 7 set 2015 alle ore 16:12 Robert Schultz <
notifications@github.com> ha scritto:

**Comment by Sembiance** [comment]
I normally don't provide duplicate data simple for convenience. I usually instead recommend a simple pre-processing script on your side that will extract the necessary data, once, whenever the site updates, then saving the data you were after in a static format somewhere in your DB or whatnot.

**Comment by marcobuschini** [comment]
Well, I am not thinking about a website, but about a mobile application. I
will consider that option, though.

Il giorno ven 11 set 2015 alle ore 01:11 Robert Schultz <
notifications@github.com> ha scritto:
