### ISSUE TITLE
BFZ now on Gatherer

### ISSUE THREAD

**Issue by ZeldaZach** [Sembiance/mtgjson#73]
Just a note for you, like usual

**Comment by Sembiance** [comment]
Hello

While I do appreciate the heads up on new sets on gatherer, I have an automated script that notifies me within 1 hour of a new set being added to Gatherer. So again, while I appreciate the effort, I'm often already working on the new set when you submit the new set github issue. So you may want to give me 24 hours or so before submitting an issue, as I'll likely have the new set up before then, that way you don't have to waste any time on your side submitting an issue :)

**Comment by ZeldaZach** [comment]
Awesome, thanks for the notice, Robert!

**Comment by rotaercz** [comment]
I actually really appreciate Zach's heads up. It's like a mailing list
informing everyone that a new set is up and there will be new json data up
soon. :)

**Comment by Sembiance** [comment]
@rotaercz I'll try and create a new issue on github whenever I add a new set to MTGJSON.

**Comment by ZeldaZach** [comment]
Sorry I couldn't be of more help

**Comment by rotaercz** [comment]
Oh ok, thank you!
