### ISSUE TITLE
BFZ Legalities missing

### ISSUE THREAD

**Issue by jenjia** [Sembiance/mtgjson#77]
As the title says, they are missing and also:

EXP - Canopy Vista doesn't have Legalities
EXP - Cinder Glade doesn't have Legalities
EXP - Prairie Stream doesn't have Legalities
EXP - Smoldering Marsh doesn't have Legalities
EXP - Sunken Hollow doesn't have Legalities

**Comment by Sembiance** [comment]
Legalities come from Gatherer and they don't have legalities for sets until after they are officially released.

Once Gatherer has legalities for this set I'll update mtgjson.

**Comment by Sembiance** [comment]
Fixed.
